export const IDENTIFIERS = {
    FILES_LOADED: "FILES_LOADED",
    SPINE_CREATED: "SPINE_CREATED",
    START_ANIMATION: "START_ANIMATION",
    SPINE_SCALE_CHANGE: "SPINE_SCALE_CHANGE",
    DEBUG_OPTION_CHANGE: "DEBUG_OPTION_CHANGE",
    COORDS_CHANGE: "COORDS_CHANGE",
    SCALE_RANGE_CHANGE: "SCALE_RANGE_CHANGE",
    SETUP_POSE: "SETUP_POSE",
    DESTROY_PIXI_APP: "DESTROY_PIXI_APP",
    TIMELINE_PLAY: "TIMELINE_PLAY",
    SKIN_CHANGE: "SKIN_CHANGE",
    SET_MIXIN: "SET_MIXIN",
    SET_CANVAS_BACKGROUND: "SET_CANVAS_BACKGROUND"
};